#!/usr/bin/env bash
set -euo pipefail

# Run clangd's syntax check for a single file.
# This is meant to mirror the editor's clangd config (.clangd) and provide
# a machine-readable log for the agent/operator.
#
# Usage:
#   scripts/clangd_check.sh /abs/path/to/file.cu
#   scripts/clangd_check.sh include/flashinfer/foo.cuh
#
# Output:
#   - writes diagnostics to: ${CLANGD_DIAG_LOG} (default: /tmp/clangd-diag.log)

CLANGD_BIN="${CLANGD_BIN:-clangd}"
CLANGD_DIAG_LOG="${CLANGD_DIAG_LOG:-/tmp/clangd-diag.log}"

if [[ $# -ne 1 ]]; then
  echo "usage: $0 <file>" >&2
  exit 2
fi

FILE="$1"
if [[ "${FILE}" != /* ]]; then
  FILE="$(pwd)/${FILE}"
fi

if [[ ! -f "${FILE}" ]]; then
  echo "file not found: ${FILE}" >&2
  exit 2
fi

CHECK_FILE="${FILE}"
TMP_WRAP=""
case "${FILE}" in
  *.h|*.hpp|*.cuh|*.inl)
    # clangd --check expects a translation unit. For headers, generate a tiny
    # wrapper TU that includes the header by absolute path.
    # Put it under the nearest directory containing a .clangd so config applies.
    ROOT="$(dirname "${FILE}")"
    while [[ "${ROOT}" != "/" && ! -f "${ROOT}/.clangd" ]]; do
      ROOT="$(dirname "${ROOT}")"
    done
    if [[ "${ROOT}" == "/" ]]; then
      ROOT="/tmp"
    fi
    TMP_WRAP="${ROOT}/.clangd_check_wrap_$$.cu"
    cat > "${TMP_WRAP}" <<EOF
// Auto-generated by scripts/clangd_check.sh
#include "${FILE}"
int __flashinfer_clangd_check_dummy() { return 0; }
EOF
    CHECK_FILE="${TMP_WRAP}"
    ;;
esac

TS="$(date +%Y%m%d_%H%M%S)"
{
  echo "=== clangd --check @ ${TS} ==="
  echo "clangd: $(${CLANGD_BIN} --version 2>/dev/null | head -n 1 || echo "${CLANGD_BIN}")"
  echo "file: ${FILE}"
  if [[ -n "${TMP_WRAP}" ]]; then
    echo "wrapped_as: ${CHECK_FILE}"
  fi
  echo
  "${CLANGD_BIN}" --check="${CHECK_FILE}" --log=error 2>&1 || true
  echo
} | tee "${CLANGD_DIAG_LOG}" >/dev/null

if [[ -n "${TMP_WRAP}" ]]; then
  rm -f "${TMP_WRAP}" || true
fi

echo "wrote: ${CLANGD_DIAG_LOG}"
